name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push User service image
      uses: docker/docker/build-push-action@v5
      with:
        context: /home/diksha/ecommerce/ecommerce-microservice/services/user-service
        push: true
        tags: diksha307/user-service:latest
        
    - name: Build and push Product service image
      uses: docker/docker/build-push-action@v5
      with:
        context: /home/diksha/ecommerce/ecommerce-microservice/services/product-service
        push: true
        tags: diksha307/product-service:latest
        
    - name: Build and push order service image
      uses: docker/docker/build-push-action@v5
      with:
        context: /home/diksha/ecommerce/ecommerce-microservice/services/order-service
        push: true
        tags: diksha307/order-service:latest
        
      


